services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: starship
      MYSQL_ROOT_PASSWORD: secret
    # NOTE: use of "mysql_native_password" is not recommended:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker_data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  server:
    build:
      context: .
    restart: always
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: starship

volumes:
  ".docker_data":
