services:
  mysqldb:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    secrets:
      - source: mysql_root_password

  server:
    build:
      context: .
    restart: always
    env_file: .env
    ports:
      - ${SERVER_PORT}:${FORWARDED_PORT}
    secrets:
      - source: mysql_root_password

volumes:
  mysql:

secrets:
      mysql_root_password:
        file: .secrets/mysql_root_password
