version: "3"

services:
  db:
    image: postgres:15.2-alpine3.17
    env_file: .env
    hostname: db
    # volumes:
    #   - postgres:${PGDATA}
    ports:
      - 5432:5432
    secrets:
      - source: postgres_root_password
    networks:
      - default

  server:
    build:
      context: .
    env_file: .env
    ports:
      - ${SERVER_PORT}:${FORWARDED_PORT}
    secrets:
      - source: postgres_root_password
      - source: secret_key
    networks:
      - default


volumes:
  postgres:

secrets:
      postgres_root_password:
        file: .secrets/postgres_root_password
      secret_key:
        file: .secrets/secret_key

networks:
  default:
    driver: bridge
