version: "3"

services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    secrets:
      - source: mysql_root_password

  server:
    build:
      context: .
    env_file: .env
    ports:
      - ${SERVER_PORT}:${FORWARDED_PORT}
    secrets:
      - source: mysql_root_password
      - source: secret_key
    restart: on-failure


volumes:
  mysql:

secrets:
      mysql_root_password:
        file: .secrets/mysql_root_password
      secret_key:
        file: .secrets/secret_key
